version: '3'

services:
  apache:
    image: 'php:7.4-apache'
    container_name: Router
    ports:
      - '81:80'
    volumes:
      - .:/var/www/html


  # services:
  # apache:
  #   image: 'nginx:latest'
  #   container_name: Router
  #   restart: always
  #   ports:
  #     - '80:80'
  #   volumes:
  #    - .:/www
  #     - ./site.conf:/etc/nginx/conf.d/site.conf
  #   links:
  #     - php
  # php:
  #   image: php:7.4-fpm
  #   container_name: php-fpm
  #   expose:
  #     - 9000
  #   volumes:
  #     - .:/var/www/html