name: documentation

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v1

      - name: Cache phpDocumentor build files
        id: phpdocumentor-cache
        uses: actions/cache@v3
        with:
          path: .phpdoc/cache
          key: ${{ runner.os }}-phpdocumentor-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpdocumentor-

      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.php$')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Modified PHP files: $CHANGED_FILES" # Adiciona esta linha para imprimir a lista de arquivos modificados

      - name: Build with phpDocumentor
        if: env.CHANGED_FILES != ''
        run: |
          docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --target docs --cache-folder .phpdoc/cache --template default --file $(echo $CHANGED_FILES)

      - name: List contents of docs
        if: env.CHANGED_FILES != ''
        run: ls -la docs

      - name: Check size of docs folder
        if: env.CHANGED_FILES != ''
        run: du -sh docs

      - name: Upload artifact to GitHub Pages
        if: env.CHANGED_FILES != ''
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
